name: Phils
favicon: null
layout_spectrum: 0.9236562238074839
typography_spectrum: 0.39637782936915755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9415835402905941
  lightness: 0.6900176079943776
  saturation: 0.003066477132961154
  rhythmicContrast: 0.2130361320450902
purpose: []
